# This AppVeyor project is run manually, to push a new release to the Maven Central Repository.
#
# This follows the 3-project AppVeyor/Maven pattern established in https://github.com/dblock/log4jna/blob/master/AppVeyorMavenRelease.md

# https://www.appveyor.com/docs/build-environment/#java
image: Visual Studio 2019

# Use the MSYS version of gpg, instead of the version bundled with git
init:
  - set PATH=C:\msys64\usr\bin;%PATH%
  # Allow RDP connections into the build
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  M2: $(USERPROFILE)\.m2
  SETTINGS_ENC: $(APPVEYOR_BUILD_FOLDER)\build\Maven\settings.xml.enc
  SETTINGS_SEC_ENC: $(APPVEYOR_BUILD_FOLDER)\build\Maven\settings-security.xml.enc
  M2_SETTINGS: $(USERPROFILE)\.m2\settings.xml
  M2_SETTINGS_SEC: $(USERPROFILE)\.m2\settings-security.xml
  GNUPG_HOME: $(USERPROFILE)\.gnupg
  PUB_KEY_FILE_ENC: $(APPVEYOR_BUILD_FOLDER)\build\Maven\OpenSourceAquatics.public.gpg.asc.enc
  SEC_KEY_FILE_ENC: $(APPVEYOR_BUILD_FOLDER)\build\Maven\OpenSourceAquatics.secret.gpg.asc.enc
  PUB_KEY_FILE_GPG: $(USERPROFILE)\OpenSourceAquatics.public.gpg.asc
  SEC_KEY_FILE_GPG: $(USERPROFILE)\OpenSourceAquatics.secret.gpg.asc
  VERSION_INFO_PATH: src\main\java\com\aquaticinformatics\aquarius\sdk\helpers\SdkServiceClient.java
  VERSION_INFO_TARGET: <<VERSION_PLACEHOLDER>>
  
  GITHUB_AUTH_TOKEN:
    secure: e24gj/T2VZ5R4XwbNUwj+eu4FbHEqWKUhuvNKXcp4dRPxj8lgW3AbWgSitK5kzek

  passphrase:
    secure: WYu06hjvbgjSQERvZN+jZNj8RBPsxpaaAmvWUHtNzSA=

  access_token:
    secure: DeTORL7H+5KS+KHQDt52OCT0LsvkYIIPZdA0VfvWpQo7za9ZwLoHMmz76jkYOxpO

  # Salts for the four files
  settings_salt:
    secure: IRCYVm6KZUIHfsgo0cpz6CtB2uJbRpSxeoLGxfS/qnHAYkR1/BkdY7ywddoKsHwvDbi2gGLJ58hhBo5m632CLQ==

  settings_security_salt:
    secure: 1Ce+FUEP+Riv+Y3IY+MIbNlzYhKp/99PMuaudib0vMj/agOkGLeh5r2X+lUdcGEvKWUdVWMkWSRtLGR3VFOk/g==

  public_gpg_salt:
    secure: tIc77vjrRocUe9zDzjsSEKI3/5nuvrJDoKV/VzlH7jfuxRKUc20lWI5Y0wjN2ZDxX4OtAsefHyPcm+aGdi3gAQ==

  secret_gpg_salt:
    secure: XoQzJ7kTuPXGUQ2S7oeSgqWfUmZ5sFtOK4r+h4yupr1C9Mk7QYvrP3pP053VJ3WIFWH4jee6jtfpCMfcVmCG0g==


install:
  # Log versions for debugging
  - where java
  - java -version
  - where mvn
  - mvn --version
  - where gpg
  - gpg --version

  # Install secure-file and decrypt everything
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))

  # Might need to create output folders if they don't already exist
  - ps: |
      if(!(Test-Path -Path $env:M2)) {
                New-Item $env:M2 -type directory -Verbose
      }

  # Now we can decrypt to the correct destination
  - cmd: appveyor-tools\secure-file -secret %passphrase% -decrypt %SETTINGS_ENC% -salt %settings_salt% -out %M2_SETTINGS%
  - cmd: appveyor-tools\secure-file -secret %passphrase% -decrypt %SETTINGS_SEC_ENC% -salt %settings_security_salt% -out %M2_SETTINGS_SEC%
  - cmd: appveyor-tools\secure-file -secret %passphrase% -decrypt %PUB_KEY_FILE_ENC% -salt %public_gpg_salt% -out %PUB_KEY_FILE_GPG%
  - cmd: appveyor-tools\secure-file -secret %passphrase% -decrypt %SEC_KEY_FILE_ENC% -salt %secret_gpg_salt% -out %SEC_KEY_FILE_GPG%

  # install gpg keys
  - gpg --import %PUB_KEY_FILE_GPG%
  - gpg --batch --import %SEC_KEY_FILE_GPG%

# This script is launched manually
build: off

build_script:
  - ps: (Get-Content "$env:VERSION_INFO_PATH").replace("$env:VERSION_INFO_TARGET", "$env:APPVEYOR_BUILD_VERSION") | Set-Content "$env:VERSION_INFO_PATH"
  - mvn -B site site:stage deploy -P release -Drevision=%APPVEYOR_BUILD_VERSION%

# Maven runs the tests as part of the build, so we don't need to run them again
test: off

# Create a tag for successful builds and push it to the repo
artifacts:
  - path: target\aquarius.sdk-*.jar
    name: AllPackages

deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_BUILD_VERSION)
    release: AQUARIUS SDK $(APPVEYOR_BUILD_VERSION)
    description: ''
    artifact: AllPackages
    auth_token: $(GITHUB_AUTH_TOKEN)
    on:
      branch: master

cache:
  # Cache Maven and m.2
  - '%MAVEN_HOME%'
  - '%M2%'
